
#公共配置与profiles选择无关 mapperLocations指的路径是src/main/resources
mybatis:
  typeAliasesPackage: com.xdd.entity
  mapperLocations: classpath:mapper/*.xml

---

#开发配置
spring:
  profiles:
  active: prod
  resources:
    static-locations: classpath:static/,file:static/


  datasource:
    url: jdbc:mysql://localhost:3306/shiro
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
  druid:
    # 下面为连接池的补充设置，应用到上面所有数据源中
    # 初始化大小，最小，最大
    initial-size: 5
    min-idle: 5
    max-active: 20
    # 配置获取连接等待超时的时间
    max-wait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    time-between-eviction-runs-millis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    min-evictable-idle-time-millis: 300000
    validation-query: SELECT 1 FROM DUAL
    test-while-idle: true
    test-on-borrow: false
    test-on-return: false
    #是否开启PSCache，PSCache对支持游标的数据库性能提升巨大，oracle建议开启，mysql下建议关闭
    pool-prepared-statements: true
    #   配置监控统计拦截的filters，去掉后监控界面sql无法统计，wall:用于防火墙,防御sql注入.stat:监控统计
    max-pool-prepared-statement-per-connection-size: 20
    filters: stat,wall
    use-global-data-source-stat: true
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connect-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      #      # 配置监控服务器
      #      stat-view-servlet:
      #        login-username: admin
      #        login-password: 123456
      #        reset-enable: false
      #        url-pattern: /druid/*
      #        # 添加IP白名单
      #        allow: 10.62.2.71
      #        # 添加IP黑名单，当白名单和黑名单重复时，黑名单优先级更高
      #        #deny:
      #      web-stat-filter:
      #        # 添加过滤规则
      #        url-pattern: /*
      #        # 忽略过滤格式
      #        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"


  #对redis的配置
  redis:
      host: 10.62.2.71
      port: 6379
      timeout: 20000
      password:
      pool:
      max-idle: 100
      min-idle: 1
      max-active: 1000
      max-wait: -1

      #对日志文件的配置
      logging:
      config: classpath:logback-spring.xml

